class structtype():
    No_of_Server = []
    No_of_VM = []
    VC_limit = []
    VM_limit = []
    PC_Value = []
    PM_Value = []
    VC = []
    VM = []
    PC = []
    PM = []
    Pmax = []
    BW = []
    Active_Servers = []
    no_of_tasks = []
